# Generated by Django 5.2.3 on 2025-10-07 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_meeting_start_time_alter_member_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2025, 10, 7, 20, 21, 4, 759826)),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_on',
            field=models.DateField(default=datetime.datetime(2025, 10, 7, 20, 21, 4, 759507, tzinfo=datetime.timezone.utc)),
        ),
    ]
