# Generated by Django 5.2.15 on 2026-06-13 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_meeting_start_time_alter_member_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2026, 6, 13, 14, 39, 1, 498089)),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_on',
            field=models.DateField(default=datetime.datetime(2026, 6, 13, 9, 9, 1, 497835, tzinfo=datetime.timezone.utc)),
        ),
    ]
