# Generated by Django 5.2.15 on 2026-07-24 16:45

import datetime
import django.utils.timezone
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_meeting_start_time_alter_member_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='file',
            field=models.FileField(upload_to=tracker.models.contribution_upload_path),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
