# Generated by Django 5.2.3 on 2025-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('model_file', models.FileField(blank=True, null=True, upload_to='AAAS/models/')),
                ('documentation_file', models.FileField(blank=True, null=True, upload_to='AAAS/documentation/')),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='AAAS/datasets/')),
                ('code_file', models.FileField(blank=True, null=True, upload_to='AAAS/code/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('register_no', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
