# Generated by Django 5.2.3 on 2025-10-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaas',
            name='register_no',
            field=models.PositiveIntegerField(),
        ),
    ]
