# Generated by Django 5.2.15 on 2026-06-13 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 11, 45, 45, 839702)),
        ),
    ]
