# Generated by Django 5.2.15 on 2026-06-13 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 13, 14, 39, 1, 496051)),
        ),
    ]
