# Generated by Django 5.2.15 on 2026-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_account_password_alter_member_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='posts',
            field=models.TextField(default='[0]'),
        ),
        migrations.AlterField(
            model_name='member',
            name='posts',
            field=models.TextField(default='[0]'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
