# Generated by Django 5.2.15 on 2026-07-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_joinrequest_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='applicant_reg_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
